### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shi-an** [ImZjm/LiteLoaderQQNT-Message-Show#1]
轻量工具箱的消息时间也显示在消息左侧了
![image](https://github.com/ImZjm/LiteLoaderQQNT-Message-Show/assets/79352488/ff89ee58-fbff-4415-a760-998096b9c101)

**Comment by ImZjm** [comment]
### emm...  轻量工具箱下架了，能不能提供一下

![image](https://github.com/ImZjm/LiteLoaderQQNT-Message-Show/assets/63181114/7396c669-a748-4f8b-a6fe-0ccf29dc1f59)
我这里没有

**Comment by shi-an** [comment]
https://wwgy.lanzouy.com/iOgWk151zjob

**Comment by ImZjm** [comment]
## 已修，在插件市场内更新并重启就好✔😊
![image](https://github.com/ImZjm/LiteLoaderQQNT-Message-Show/assets/63181114/48956a2e-5240-4f71-a9df-031f6a70c851)
