### ISSUE TITLE
样式

### ISSUE THREAD

**Issue by shi-an** [ImZjm/LiteLoaderQQNT-Message-Show#2]
开启靠左显示  两个气泡贴在一起了
![image](https://github.com/ImZjm/LiteLoaderQQNT-Message-Show/assets/79352488/0f5bfdf9-bbc6-46ad-98d3-08bff63106b2)
![image](https://github.com/ImZjm/LiteLoaderQQNT-Message-Show/assets/79352488/62762d24-e05d-47b1-b40b-0b85206b2d07)

**Comment by ImZjm** [comment]
抱歉，没有及时处理
已修复，插件市场更新即可
